name: Deploy devumum.opendesa.id
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Jadwalkan setiap 6 jam

jobs:
  build:
    name: Deployment Website devumum.opendesa.id
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: SSH Remote
        uses: fifsky/ssh-action@master
        with:
          host: devumum.opendesa.id
          user: ${{ secrets.SSH_USER_DEVUMUM }}
          pass: ${{ secrets.SSH_PASS_DEVUMUM }}
          port: ${{ secrets.SSH_PORT }}
          command: |
            cd /home/devumum.opendesa.id/public_html

            # Restore to the state of the remote branch
            git fetch origin dev
            git reset --hard origin/dev
            git pull origin dev

            # Run PHP script to restore database
            php index.php job restore
